<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../general.css">
    <title>Title</title>
</head>
<body>
<table id="product-list">
    <caption>Product list</caption>
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Image</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($products as $product): ?>
        <tr>
            <td><?php echo $product->id; ?></td>
            <td><?php echo $product->name; ?></td>
            <td><?php echo $product->description; ?></td>
            <td><?php echo $product->price; ?></td>
            <td><?php echo $product->image; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</body>
</html>